### ISSUE TITLE
Native dataset missing from master data dictionary

### ISSUE THREAD

**Issue by jasonlally** [DataSF/metadata-mgmt-tool#7]
https://data.sfgov.org/City-Infrastructure/Right-of-Way-Polygons/a2mg-gwmg is missing. The underlying type is gismap, not sure if that has anything to do with the issue.

**Comment by j9recurses** [comment]
This is fixed now. This dataset wasn't loading because of the attachment url that had special characters in it. 

Go to https://data.sfgov.org/City-Management-and-Ethics/Master-Data-Dictionary/8zp7-ik63/data and then search for the 4x4:  a2mg-gwmg
